// Built-in Flugo file chooser service wrapper.
// This file is generated by flugo codegen — DO NOT EDIT.

import 'dart:convert';
import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:url_launcher/url_launcher.dart';

import 'bridge.gen.dart';

/// Flugo's native file-chooser channel (Android). Handles the Storage Access
/// Framework "save" and "reveal folder" flows natively so the real content://
/// URI is captured — file_picker discards it and returns a fabricated path,
/// which makes "open folder" land in the wrong place.
const MethodChannel _fcChannel = MethodChannel('flugo/filechooser');

/// Result of a file save operation. Contains everything the developer needs
/// to build a success dialog without platform checks.
class SaveFileResult {
  const SaveFileResult({
    this.tempPath,
    this.savedPath,
    this.cancelled = false,
    this.exists = false,
    this.error,
  });

  /// Where the file was initially written (temp path on mobile/Flatpak, same as savedPath on native).
  /// Use this path for [FileChooserService.shareFile] on mobile.
  final String? tempPath;

  /// The final destination path chosen by the user (or same as tempPath on native desktop).
  /// Use this path for display and [FileChooserService.openDirectory].
  final String? savedPath;

  /// Whether the user cancelled the save dialog (only possible on mobile/Flatpak).
  final bool cancelled;

  /// File already exists at the target path (native desktop only).
  /// When true, the file was NOT written. Show a confirmation dialog,
  /// then call the Go function again with force=true if the user confirms.
  final bool exists;

  /// Error message if the save failed.
  final String? error;

  /// Convenience check: save completed successfully.
  bool get ok => savedPath != null && error == null && !cancelled && !exists;
}

/// Cross-platform file chooser service.
///
/// On Linux, uses XDG Desktop Portal via the Go backend (works in Flatpak/containers).
/// On all other platforms, uses the file_picker and url_launcher plugins.
class FileChooserService {
  /// Pick a single file.
  /// Returns the chosen path, or null if the user cancelled.
  Future<String?> pickFile(String title) async {
    if (Platform.isLinux) {
      final response = await FlugoBridge.callAsync(
        'FileChooserService.PickFile',
        [title],
      );
      final result = FlugoBridge.decodeResponse(response);
      if (result == null || result == '') return null;
      return result as String;
    }

    final result = await FilePicker.platform.pickFiles(dialogTitle: title);
    if (result == null) return null;
    return result.files.single.path;
  }

  /// Pick multiple files.
  /// Returns the chosen paths, or null if the user cancelled.
  Future<List<String>?> pickFiles(String title) async {
    if (Platform.isLinux) {
      final response = await FlugoBridge.callAsync(
        'FileChooserService.PickFiles',
        [title],
      );
      final result = FlugoBridge.decodeResponse(response);
      if (result == null) return null;
      return (result as List).map((e) => e as String).toList();
    }

    final result = await FilePicker.platform.pickFiles(
      dialogTitle: title,
      allowMultiple: true,
    );
    if (result == null) return null;
    return result.files.map((f) => f.path!).where((p) => p.isNotEmpty).toList();
  }

  /// Pick a directory.
  /// Returns the chosen path, or null if the user cancelled.
  Future<String?> pickDirectory(String title) async {
    if (Platform.isLinux) {
      final response = await FlugoBridge.callAsync(
        'FileChooserService.PickDirectory',
        [title],
      );
      final result = FlugoBridge.decodeResponse(response);
      if (result == null || result == '') return null;
      return result as String;
    }

    return FilePicker.platform.getDirectoryPath(dialogTitle: title);
  }

  /// Show a save file dialog.
  ///
  /// When [bytes] is provided, the file is written automatically on all platforms.
  /// On Android/iOS, [bytes] is required by the platform — omitting it will fail.
  ///
  /// When [targetPath] is provided, the file is written directly to that path
  /// without showing a dialog — unless the app is running inside a Flatpak
  /// sandbox, in which case the portal dialog is shown instead (sandbox
  /// restrictions require portal-granted paths).
  ///
  /// Returns a [SaveFileResult] with tempPath (for sharing) and savedPath (for display).
  Future<SaveFileResult> saveFile(
    String title,
    String suggestedName,
    String directory, {
    Uint8List? bytes,
    String? targetPath,
  }) async {
    if (Platform.isLinux) {
      final response = await FlugoBridge.callAsync(
        'FileChooserService.SaveFile',
        [title, suggestedName, directory, targetPath ?? ''],
      );
      final result = FlugoBridge.decodeResponse(response);
      if (result == null || result == '') {
        return const SaveFileResult(cancelled: true);
      }
      final path = result as String;
      if (bytes != null) {
        await File(path).writeAsBytes(bytes);
      }
      return SaveFileResult(tempPath: targetPath ?? path, savedPath: path);
    }

    // Non-Linux with targetPath
    if (targetPath != null && targetPath.isNotEmpty) {
      // Mobile: write to targetPath (app sandbox), then show SAF dialog
      if (Platform.isAndroid || Platform.isIOS) {
        if (bytes != null) {
          await File(targetPath).writeAsBytes(bytes);
        }
        final fileName = targetPath.split(Platform.pathSeparator).last;
        // Android: native SAF save returns the real content:// URI so the
        // folder can later be revealed at its true location.
        if (Platform.isAndroid) {
          final uri = await _saveDocument(fileName, targetPath);
          if (uri == null) {
            return SaveFileResult(cancelled: true, tempPath: targetPath);
          }
          return SaveFileResult(tempPath: targetPath, savedPath: uri);
        }
        final savedBytes = await File(targetPath).readAsBytes();
        final safPath = await FilePicker.platform.saveFile(
          dialogTitle: title,
          fileName: fileName,
          bytes: savedBytes,
        );
        if (safPath == null) {
          return SaveFileResult(cancelled: true, tempPath: targetPath);
        }
        return SaveFileResult(tempPath: targetPath, savedPath: safPath);
      }
      // Desktop (macOS/Windows): write directly, no dialog
      if (bytes != null) {
        await File(targetPath).writeAsBytes(bytes);
      }
      return SaveFileResult(tempPath: targetPath, savedPath: targetPath);
    }

    // Mobile without targetPath: write to temp for sharing, then show SAF
    if (Platform.isAndroid || Platform.isIOS) {
      final tempDir = await getTemporaryDirectory();
      final id = DateTime.now().millisecondsSinceEpoch.toString();
      final tempSubDir = Directory('${tempDir.path}/flugo_tmp/$id');
      await tempSubDir.create(recursive: true);
      final tempFile = '${tempSubDir.path}/$suggestedName';
      if (bytes != null) {
        await File(tempFile).writeAsBytes(bytes);
      }
      // Android: native SAF save returns the real content:// URI.
      if (Platform.isAndroid) {
        final uri = await _saveDocument(suggestedName, tempFile);
        if (uri == null) {
          return SaveFileResult(cancelled: true, tempPath: tempFile);
        }
        return SaveFileResult(tempPath: tempFile, savedPath: uri);
      }
      final safPath = await FilePicker.platform.saveFile(
        dialogTitle: title,
        fileName: suggestedName,
        bytes: bytes,
      );
      if (safPath == null) {
        return SaveFileResult(cancelled: true, tempPath: tempFile);
      }
      return SaveFileResult(tempPath: tempFile, savedPath: safPath);
    }

    // Desktop without targetPath — show dialog
    final path = await FilePicker.platform.saveFile(
      dialogTitle: title,
      fileName: suggestedName,
      initialDirectory: directory.isNotEmpty ? directory : null,
      bytes: bytes,
    );
    if (path == null) return const SaveFileResult(cancelled: true);
    // On desktop (non-Linux), FilePicker returns a path but doesn't write.
    if (bytes != null) {
      await File(path).writeAsBytes(bytes);
    }
    return SaveFileResult(tempPath: path, savedPath: path);
  }

  /// Show a save files dialog for multiple files.
  /// Returns the chosen paths, or null if the user cancelled.
  Future<List<String>?> saveFiles(
    String title,
    List<String> filenames,
    String directory,
  ) async {
    if (Platform.isLinux) {
      final response = await FlugoBridge.callAsync(
        'FileChooserService.SaveFiles',
        [title, filenames, directory],
      );
      final result = FlugoBridge.decodeResponse(response);
      if (result == null) return null;
      return (result as List).map((e) => e as String).toList();
    }

    // file_picker doesn't support multi-save — fall back to single save per file
    final paths = <String>[];
    for (final name in filenames) {
      final result = await saveFile(title, name, directory);
      if (result.cancelled) return null;
      paths.add(result.savedPath!);
    }
    return paths;
  }

  /// Open a file with the default application.
  Future<void> openFile(String filePath) async {
    if (Platform.isLinux) {
      final response = await FlugoBridge.callAsync(
        'FileChooserService.OpenFile',
        [filePath],
      );
      FlugoBridge.decodeResponse(response);
      return;
    }

    final uri = Uri.file(filePath);
    await launchUrl(uri);
  }

  /// Open a URL (http, https, mailto, ...) with the user's default handler.
  ///
  /// On Linux this goes through the Go backend's OpenURI portal call (works
  /// in Flatpak and other sandboxes, xdg-open fallback); everywhere else it
  /// uses url_launcher. Returns false when no handler could be launched —
  /// callers should offer a fallback (e.g. show the URL with a copy button)
  /// instead of assuming the browser opened.
  Future<bool> openUrl(String url) async {
    try {
      if (Platform.isLinux) {
        final response = await FlugoBridge.callAsync(
          'FileChooserService.OpenURL',
          [url],
        );
        FlugoBridge.decodeResponse(response);
        return true;
      }
      final uri = Uri.tryParse(url);
      if (uri == null) return false;
      return await launchUrl(uri, mode: LaunchMode.externalApplication);
    } catch (_) {
      return false;
    }
  }

  /// Android-only: run the native SAF create-document dialog, streaming the
  /// file at [sourcePath] into the chosen destination, and return its real
  /// content:// URI (or null if the user cancelled). This is what lets
  /// [openDirectory] later reveal the true folder — file_picker's saveFile
  /// discards the URI and returns a fabricated /storage/.../Download path.
  Future<String?> _saveDocument(String fileName, String sourcePath) {
    return _fcChannel.invokeMethod<String>('saveDocument', {
      'fileName': fileName,
      'mimeType': '*/*',
      'sourcePath': sourcePath,
    });
  }

  /// Open the containing folder of a file in the platform's file manager.
  ///
  /// Android: [filePath] is the SAF content:// URI of a saved document (from
  /// [saveFile]/[handleWriteResult]); the native channel launches the SAF picker
  /// positioned at the document's PARENT via EXTRA_INITIAL_URI. Android has no
  /// reliable intent to browse an arbitrary folder (ACTION_VIEW on a directory
  /// is unsupported by most file managers), so this positioned picker is the
  /// accepted workaround. Positioning needs API 26+; below that it opens
  /// unpositioned. Throws if no provider can handle it.
  /// iOS: opens the Files app at the directory via its shareddocuments://
  /// URL scheme.
  /// Failures (no matching activity / scheme not launchable) THROW — UIs
  /// must surface them; never leave a dead button on a silent no-op.
  Future<void> openDirectory(String filePath) async {
    if (Platform.isAndroid) {
      final ok = await _fcChannel.invokeMethod<bool>(
        'openFolder',
        {'uri': filePath},
      );
      if (ok != true) {
        throw const FileSystemException('no app can open this folder');
      }
      return;
    }

    if (Platform.isIOS) {
      final dir = File(filePath).parent.path;
      final uri = Uri.parse('shareddocuments://$dir');
      if (!await launchUrl(uri)) {
        throw FileSystemException('Files app could not open location', dir);
      }
      return;
    }

    if (Platform.isLinux) {
      final response = await FlugoBridge.callAsync(
        'FileChooserService.OpenDirectory',
        [filePath],
      );
      FlugoBridge.decodeResponse(response);
      return;
    }

    final dir = File(filePath).parent.path;
    final uri = Uri.file(dir);
    await launchUrl(uri);
  }

  /// Share a file via the platform's native share sheet.
  /// On mobile (Android/iOS), opens the system share dialog.
  /// On desktop, this is a no-op — use openDirectory() instead.
  ///
  /// share_plus copies the file into its own FileProvider cache before
  /// generating the content:// URI; it also clears that cache on every
  /// call (Share.kt:95). No need for us to pre-clear it.
  ///
  /// Throws [FileSystemException] if the source path doesn't exist —
  /// callers should catch and surface this so a missing temp file
  /// shows up as an explicit error instead of a silent no-op when the
  /// recipient app tries to read the content URI later.
  Future<void> shareFile(String filePath) async {
    if (!Platform.isAndroid && !Platform.isIOS) return;
    if (!await File(filePath).exists()) {
      throw FileSystemException('share source file does not exist', filePath);
    }
    await Share.shareXFiles([XFile(filePath)]);
  }

  /// Check if a path is on the XDG document portal FUSE mount.
  /// Always returns false on non-Linux platforms.
  Future<bool> isDocPortalPath(String path) async {
    if (!Platform.isLinux) return false;

    final response = await FlugoBridge.callAsync(
      'FileChooserService.IsDocPortalPath',
      [path],
    );
    final result = FlugoBridge.decodeResponse(response);
    return result as bool;
  }

  /// Process a [WriteResult] JSON from Go's `filechooser.WriteFile()`.
  ///
  /// On native desktop, the file is already at the final location — returns immediately.
  /// On Flatpak, shows a portal save dialog so the user picks the destination.
  /// On mobile, shows a SAF save dialog so the user picks the destination.
  ///
  /// [jsonResult] is the JSON-encoded WriteResult from the Go backend.
  /// [suggestedName] is used as the default filename in save dialogs.
  Future<SaveFileResult> handleWriteResult(
    String jsonResult,
    String suggestedName,
  ) async {
    try {
      final wr = jsonDecode(jsonResult) as Map<String, dynamic>;
      final path = wr['path'] as String;
      final env = wr['env'] as String;

      final exists = wr['exists'] as bool? ?? false;

      switch (env) {
        case 'native':
          if (exists) {
            return SaveFileResult(savedPath: path, exists: true);
          }
          return SaveFileResult(tempPath: path, savedPath: path);
        case 'mobile':
          // Android: stream the Go-written temp file straight to the SAF
          // destination via the native channel (no whole-file read into Dart
          // memory) and capture the real content:// URI for folder reveal.
          if (Platform.isAndroid) {
            final uri = await _saveDocument(suggestedName, path);
            if (uri == null) {
              return SaveFileResult(cancelled: true, tempPath: path);
            }
            return SaveFileResult(tempPath: path, savedPath: uri);
          }
          final mobileBytes = await File(path).readAsBytes();
          final mobileResult =
              await saveFile('Save File', suggestedName, '', bytes: mobileBytes);
          if (mobileResult.cancelled) {
            return SaveFileResult(cancelled: true, tempPath: path);
          }
          return SaveFileResult(tempPath: path, savedPath: mobileResult.savedPath);
        case 'flatpak':
          final bytes = await File(path).readAsBytes();
          final saveResult = await saveFile('Save File', suggestedName, '', bytes: bytes);
          if (saveResult.cancelled) {
            return SaveFileResult(cancelled: true, tempPath: path);
          }
          return SaveFileResult(tempPath: path, savedPath: saveResult.savedPath);
        default:
          return SaveFileResult(error: 'Unknown environment: $env');
      }
    } catch (e) {
      return SaveFileResult(error: e.toString());
    }
  }

  /// Clean up the temp directory created by [handleWriteResult].
  ///
  /// Call this when the user dismisses the success dialog (e.g., presses OK).
  /// Do NOT call immediately after [shareFile] — on Android, the share sheet
  /// returns before the receiving app finishes reading the file.
  void cleanupTemp(SaveFileResult result) {
    if (result.tempPath == null) return;
    if (result.tempPath == result.savedPath) return;
    final tempDir = File(result.tempPath!).parent;
    if (tempDir.existsSync()) {
      tempDir.deleteSync(recursive: true);
    }
  }
}

/// Global instance for convenient access.
final fileChooserService = FileChooserService();
